"use client"
import './globals.css';

import React from 'react';

import { Inter } from 'next/font/google';

import DashboardCSS from '../../style/Dashboard.module.css';
import {
  BlurForSafety,
  CategoryWisedProductsStore,
  CommentPermission,
  LoggedInUserStore,
  ProductsStore,
  UserStore,
} from '../../userStore';
import BeeRawNavbar from '../Components/BeeRawNavbar';
import CustomerSidebar from '../Components/CustomerSidebar';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <CommentPermission.Provider>
    <LoggedInUserStore.Provider>
    <BlurForSafety.Provider>
    <ProductsStore.Provider>
      <CategoryWisedProductsStore.Provider>
        <UserStore.Provider>
          <html lang="en">
            <body style={{ background: 'black', fontFamily: 'sans-serif' }} className='text-white'>
              <div className="flex">
                <div style={{ position: 'fixed', height: '100%' }} className='hidden lg:block'>
                  <CustomerSidebar></CustomerSidebar>
                </div>

                <div className={`w-full lg:ml-[310px] ${DashboardCSS.sidebarBackground} lg:px-[48px] px-[10px] min-h-screen`}>
                  <BeeRawNavbar></BeeRawNavbar>
                  <div>
                    {children}
                  </div>
                </div>
              </div>
            </body>
          </html>
        </UserStore.Provider>
      </CategoryWisedProductsStore.Provider>
    </ProductsStore.Provider>
    </BlurForSafety.Provider>
    </LoggedInUserStore.Provider>
    </CommentPermission.Provider>
  )
}
